initial commit
Zaykka/2022-2-VK-EDU-FS-Frontend-S-Serebryakova pull request #9
Opened 2022-12-29 17:28 UTC by Zaykka

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
*
*

2022-12-29 17:30 UTC, HaseProgram commented
- [ ] В корневой папке репозитория создать базовое приложение `exam` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) по инструкции выше
- [ ] Сверстать 2 страницы и необходимые компоненты. Использовать стили
- [ ] Реализовать перевод с одного языка на другой (хорошо, если можно будет выбрать язык из выпадающего списка)
- [ ] Реализовать перевод с неизвестного языка (автоопределитель из `API`)
- [ ] Сохранять историю переводов в `localStorage`
- [ ] Использовать `Redux`
- [ ] Использовать `React-router` для перехода между страницами
- [ ] Задеплоить решение, используя `GitHub Actions`.
- [ ] Теория: Объяснить, почему были использованы те или иные инструменты, участки кода и механизмы при решении задачи. Ответить на теоретические вопросы (пункт выполняется лично с преподавателем)
- [ ] Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно)

2022-12-29 17:37 UTC, HaseProgram requested changes

2022-12-29 17:37 UTC, HaseProgram commented on exam/src/pages/PageMain/PageMain.jsx
> +    }
Можно и не использовать

2022-12-29 17:37 UTC, HaseProgram commented on exam/src/pages/PageMain/PageMain.jsx
> +        setTranslations([...translations, { ...translation, id: Date.now() }]);
id не нужен

2022-12-29 17:37 UTC, HaseProgram commented on exam/src/pages/PageMain/PageMain.jsx
> +                            onSubmit={handleSubmit}
проверить, действительно есть ли событие onSubmit (возможно есть только у элемента <form>)

2022-12-29 17:39 UTC, HaseProgram commented on exam/src/components/Header/Header.jsx
> +import React, { useState, useEffect } from 'react'
useState, useEffect  - лишние

2022-12-31 13:46 UTC, HaseProgram commented on exam/src/index.js
> +let store = createStore(reducer);
Это надо все-таки в отдельные файлы помещать, не стоит совмещать все в одном

2022-12-31 13:48 UTC, HaseProgram commented on exam/src/components/Source/utils.js
> +}
Лучше оформить как  action

2022-12-31 13:52 UTC, HaseProgram commented on exam/src/pages/PageHistory/PageHistory.jsx
> +        }
Можно такие записи делать короче)
```JavaScript
const savedTranslations = getTranslationsFromLocalStorage() || []
setTranslations(savedTranslations);
```

2022-12-31 13:59 UTC, HaseProgram requested changes, later dismissed
Нужны правки)

В основном - по редаксу. У нас должно быть как минимум 2 директории - actions и reducers, совсем хорошо бы вынести еще в константы actionTypes.

2023-01-01 12:43 UTC, martinkomitsky approved these changes
40

2023-01-01 12:43 UTC, merged